name: Go Multi-Platform Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        goos: [darwin, linux]
        goarch: [amd64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21
      - name: Set environment variables
        run: |
          echo "GOOS=${{ matrix.goos }}" >> $GITHUB_ENV
          echo "GOARCH=${{ matrix.goarch }}" >> $GITHUB_ENV
      - name: Install dependencies
        run: go mod tidy
      - name: Build application
        run: go build -o warp-${{ matrix.goos }}-${{ matrix.goarch }} ./cmd/app/.
      - name: Upload binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: warp-${{ matrix.goos }}-${{ matrix.goarch }}
          path: ./warp-${{ matrix.goos }}-${{ matrix.goarch }}
    
  release:
    needs: build-and-release
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      - uses: ncipollo/release-action@v1
        with:
          name: Release ${{ github.ref_name }}
          tag: ${{ github.ref_name }}
          artifacts: "artifacts/*/*"
          body: "Automated release for tag ${{ github.ref_name }}."
          allowUpdates: true
          replaceArtifacts: true
